name: 3 tier-application-CICD
on: [push]
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: cloning repo
        uses: actions/checkout@v3
      - name: Docker login
        uses:  docker/login-action@v3
        with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: frontend
          tags: ${{ vars.DOCKERHUB_USERNAME }}/3-tier-react-app:frontend_1.0

  build_backend:
      runs-on: ubuntu-latest
      steps:
          - name: cloning repo
            uses: actions/checkout@v3
          - name: Docker login
            uses:  docker/login-action@v3
            with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build image
            uses: docker/build-push-action@v6
            with:
              push: true
              context: backend
              tags: ${{ vars.DOCKERHUB_USERNAME }}/3-tier-react-app:backend_1.0

  deploy:
      needs: [build_frontend , build_backend]
      runs-on: ubuntu-latest
      steps:
        - name: Setup-SSH-key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@43.205.96.33
            git clone https://github.com/Rohit-Chavan29/3-tier-react-app.git
            echo "Succefully Cloned"
            pwd
            hostname
            docker-compose down
            docker-compose up -d



