name: 3 tier-application-CICD
on: [push]
jobs:
  build_frontend:
    runs-on: ubunto-latest
    steps:
      - name: cloning repo
        uses: actions/checkout@v3
      - name: Docker login
        uses:  docker/login-action@v3
        with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: frontend
          tags: ${{ vars.DOCKERHUB_USERNAME }}/3-tier-react-app:frontend_1.0

  build_backend:
      runs-on: ubunto:latest
      steps:
          - name: cloning repo
            uses: actions/checkout@v3
          - name: Docker login
            uses:  docker/login-action@v3
            with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build image
            uses: docker/build-push-action@v6
            with:
              push: true
              context: backend
              tags: ${{ vars.DOCKERHUB_USERNAME }}/3-tier-react-app:backend_1.0



